spring.application.name=doctorss

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/doctorss}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:2005}
spring.jpa.show-sql=true

server.error.include-stacktrace=never
server.error.include-message=never

api.security.token.secret=${JWT_SECRET:12345678}